### ISSUE TITLE
!FONTOS!

### ISSUE THREAD

**Issue by skidoodle** [skidoodle/ekreta-src#14]
Sziasztok.
Koszi a Pull Requesteket, kerlek *szavazzatok meg* hogy mergeljem-e masterba vagy hagyjam meg az eredeti codebaset, esetleg csinaljak kulon branchet a *tovabbfejlesztett* valtozatnak.
Koszi

**Comment by blackPantherOS** [comment]
Fricskának jó ez, de egy sok sok milliárdos fejlesztésbe miért akarna bárki hosszútávon ingyenmunkát végezni, hogy a NER kegyeltjei tovább gazdagodjanak, és kizsákmányoljanak?

**Comment by skidoodle** [comment]
> Fricskának jó ez, de egy sok sok milliárdos fejlesztésbe miért akarna bárki hosszútávon ingyenmunkát végezni, hogy a NER kegyeltjei tovább gazdagodjanak, és kizsákmányoljanak? Talán majd az oktatási rendszer valós reformja után!

jogos, de nem tudom mi lenne a helyes megoldas jelen pillanatban, hagyjam az egeszet ugy ahogy van, vagy mergeljem a modositasokat amiket kuldenek ezzel elveszitve az eredeti forraskodot :/

**Comment by skidoodle** [comment]
Itt tudtok szavazni, hogy mi legyen: https://github.com/skidoodle/ekreta-src/discussions/16

ha addig nem kapok dmca takedownt 😂

**Comment by sarkiroka** [comment]
szerintem hagyd, úgysem lesz opensource sosem, még így sem, hogy kinn a forrás

**Comment by skidoodle** [comment]
> szerintem hagyd, úgysem lesz opensource sosem, még így sem, hogy kinn a forrás

kiderul majd a szavazasbol, hogy mi lesz de en is az eredeti kod megtartasa mellett allok.
mellesleg meno lenne egy opensource rendszer amit a magyar fejlesztok es a kozosseg csinal, jobb es biztonsagosabb lenne az biztos csak rengeteg munka es ember kell hozza, ha az meg is van akkor se mukodne mivel tobb ezer iskolaban elterjeszteni egy nem allami rendszert bonyolult.

**Comment by Xenius97** [comment]
Mindenki jobban járna, ha külsős emberek fejlesztenék tovább vagy írnának újat teljesen Open Source projectként. Vicc hogy valaki erre a kódra milliárdokat költött, inkább akkor osszák szét a Contributorok közt és ezeket az embereket rúgják ki.

**Comment by AdamMolnar4D41** [comment]
Nem emlékszem pontotsan, de a lengyeleknél valakik megcsinálták, hogy a beruházás helyett összeültek és megcsinálták ingyen. Erősen kétlem, hogy bárki használná is, de ha egyszer túl sok lesz a szabadidőnk 🤷

**Comment by skidoodle** [comment]
> Mindenki jobban járna, ha külsős emberek fejlesztenék tovább vagy írnának újat teljesen Open Source projectként. Vicc hogy valaki erre a kódra milliárdokat költött, inkább akkor osszák szét a Contributorok közt és ezeket az embereket rúgják ki.

allambacsi nem orulne szerintem egy ilyen rendszernek, nem marad meg neki par milliard a zsebeben ha ingyen fejleszti a kozosseg

**Comment by SlejmUr** [comment]
> > Mindenki jobban járna, ha külsős emberek fejlesztenék tovább vagy írnának újat teljesen Open Source projectként. Vicc hogy valaki erre a kódra milliárdokat költött, inkább akkor osszák szét a Contributorok közt és ezeket az embereket rúgják ki.
> 
> allambacsi nem orulne szerintem egy ilyen rendszernek, nem marad meg neki par milliard a zsebeben ha ingyen fejleszti a kozosseg

Nem úgy marad több ha nem kell rá költeni?

**Comment by skidoodle** [comment]
> > > Mindenki jobban járna, ha külsős emberek fejlesztenék tovább vagy írnának újat teljesen Open Source projectként. Vicc hogy valaki erre a kódra milliárdokat költött, inkább akkor osszák szét a Contributorok közt és ezeket az embereket rúgják ki.
> > 
> > 
> > allambacsi nem orulne szerintem egy ilyen rendszernek, nem marad meg neki par milliard a zsebeben ha ingyen fejleszti a kozosseg
> 
> Nem úgy marad több ha nem kell rá költeni?

de ha nem kell ra kolteni mivel ingyen fejlesztik akkor hogy ker ra tamogatast eutol amibol letudna nyulni egy par milliardot?!

**Comment by SlejmUr** [comment]
Jó, mondjuk ez igaz sajna.

**Comment by Insigne** [comment]
Ki lenne az az épeszű aki ingyen foglalkozna ezzel a vödör szarral bruh

**Comment by skidoodle** [comment]
> Ki lenne az az épeszű aki ingyen foglalkozna ezzel a vödör szarral bruh

nemhiszem hogy azok akik eddig pull requestet kuldtek tenylegesen javitani szeretnek a kretat, valoszinuleg csak poenbol van az egesz javitgatas mert remalom ez a kod.

**Comment by k3rielit** [comment]
> > Ki lenne az az épeszű aki ingyen foglalkozna ezzel a vödör szarral bruh
> 
> nemhiszem hogy azok akik eddig pull requestet kuldtek tenylegesen javitani szeretnek a kretat, valoszinuleg csak poenbol van az egesz javitgatas mert remalom ez a kod.

A main-archive, dev-meme branch-ek egész jók. Úgyse éri meg javítani, mert nem ezt fogják használni az iskolak akiknek nincs választásuk. Vagy marad a kréta és elfelejtik az egészet, vagy rebrand-elik más néven más pályázati pénzbol.

Olyan szinten nincs választásuk az iskoláknak hogy az iskolai weboldalakat is kérdés nélkul átrakta az állam egy sablonra meg egy másik domainre.

Meg nem akarok annyira negatív lenni, de open source állami dolog esélytelen. A valódi ok a pályázati pénz hiánya lenne, a hivatalos ok meg valami "biztonsági okokból" sablon válasz.

**Comment by Bal500** [comment]
> > Mindenki jobban járna, ha külsős emberek fejlesztenék tovább vagy írnának újat teljesen Open Source projectként. Vicc hogy valaki erre a kódra milliárdokat költött, inkább akkor osszák szét a Contributorok közt és ezeket az embereket rúgják ki.
> 
> allambacsi nem orulne szerintem egy ilyen rendszernek, nem marad meg neki par milliard a zsebeben ha ingyen fejleszti a kozosseg

Egyszer megvalósult valami ilyesmi, Szivacs néven. Gyakorlatilag egy KRÉTA klón volt, csak működött is. Gyorsan véget vetettek a projektnek...

**Comment by wolfmanfp** [comment]
> Egyszer megvalósult valami ilyesmi, Szivacs néven. Gyakorlatilag egy KRÉTA klón volt, csak működött is. Gyorsan véget vetettek a projektnek...

Nem klón volt, inkább egy alternatív kliens a Krétához. A repó még megvan: https://github.com/boapps/Szivacs-Naplo   
Úgy lett vége az appnak, hogy a külsős API lekérdezéseket belassították, így a hivatalos appon kívül minden más használhatatlan lett.

**Comment by jabbalaci** [comment]
Ez így jó, ahogy van. Vétek lenne hozzányúlni :)
