### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by RetNerd** [skidoodle/ekreta-src#19]
Hol vannak a tesztek MAGDI?! Hát egy falhozvert unit test nincs ebben a szétgányolt mocsokban?

**Comment by skidoodle** [comment]
ezek egybol productionon csinalnak mindent miert lenne benne teszt az a teszt hogy vagy mukodik vagy nem azt legfeljebb megint nem megy par orat a kreta

**Comment by SlejmUr** [comment]
Megoldva, lehet zárni
