### ISSUE TITLE
Dev Master helyett

### ISSUE THREAD

**Issue by SlejmUr** [skidoodle/ekreta-src#22]
Be lehet állítani mi legyen a "main" branch hogy ne lehessen masterbe commitolni.
Settings=> Branches => Swap jelecske és ez lesz:
Kiválasztod a dev-et, update, I sure. és kész

![image](https://user-images.githubusercontent.com/52343819/201327059-2c58271d-226b-46f3-86e9-c48681648b0b.png)

**Comment by skidoodle** [comment]
attol meg ugyan ugy lehet oda commitolni  tudtommal csak a dev lesz kivalasztva alapbol

**Comment by SlejmUr** [comment]
> attol meg ugyan ugy lehet oda commitolni tudtommal csak a dev lesz kivalasztva alapbol

Így van, de nem lesz hogy véletlenül rossz branch-be lesz a commit

**Comment by skidoodle** [comment]
jogos, köszi átrakom a devet defaultra
